name: electricity_app
description: ئەپڵیکەیشنی هەژمارکردنی کارەبا - Electricity Calculator App
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^10.0.2
  shared_preferences: ^2.2.2
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - images/
  #   - assets/
